import { useNavigate } from 'react-router-dom';
import './LandingPage.css';

const STATS = [
  { value: '900M+', label: 'Eligible voters' },
  { value: '7',     label: 'Election phases'  },
  { value: '28+',   label: 'States covered'   },
  { value: '24/7',  label: 'AI availability'  },
];

const FEATURES = [
  { icon: '◈', title: 'Interactive Timeline',   desc: 'All 7 election phases at a glance. Click any phase for a plain-language AI breakdown.' },
  { icon: '◎', title: 'AI Chat Assistant',       desc: 'Ask anything about Indian elections in plain language. Streamed, real-time answers.' },
  { icon: '◇', title: 'Voter IQ Quiz',           desc: '10 adaptive questions generated by Gemini. Instant explanations on wrong answers.' },
  { icon: '▣', title: 'Readiness Checklist',     desc: 'Personalised checklist for your state. Know exactly what to carry on polling day.' },
];

const PHASES = [
  { num: '01', name: 'Announcement' },
  { num: '02', name: 'MCC' },
  { num: '03', name: 'Nomination' },
  { num: '04', name: 'Scrutiny' },
  { num: '05', name: 'Withdrawal' },
  { num: '06', name: 'Voting' },
  { num: '07', name: 'Results' },
];

export default function LandingPage() {
  const navigate = useNavigate();

  return (
    <main className="landing">

      {/* ──── Hero ──────────────────────────────────────────────── */}
      <section className="hero" aria-labelledby="hero-heading">
        <div className="hero-content fade-up">

          <div className="hero-eyebrow">
            <span className="hero-eyebrow-dot" aria-hidden="true" />
            Gemini AI · Election Commission of India data
          </div>

          <h1 id="hero-heading" className="hero-title">
            Your election guide,<br />
            <span className="hero-title-muted">powered by AI.</span>
          </h1>

          <p className="hero-subtitle">
            Navigate India's 7-phase election process with confidence.
            Ask questions, explore timelines, and vote intelligently.
          </p>

          <div className="hero-actions">
            <button
              id="cta-start-tour"
              className="btn btn-primary btn-hero-primary"
              onClick={() => navigate('/onboarding')}
            >
              Get started
            </button>
            <button
              id="cta-take-quiz"
              className="btn btn-outline btn-hero-secondary"
              onClick={() => navigate('/onboarding?next=quiz')}
            >
              Take the quiz
            </button>
            <button
              id="cta-ask-question"
              className="btn btn-ghost btn-hero-secondary"
              onClick={() => navigate('/onboarding?next=chat')}
            >
              Ask a question
            </button>
          </div>

          <div className="hero-stats">
            {STATS.map(({ value, label }) => (
              <div key={label} className="stat-item">
                <span className="stat-value">{value}</span>
                <span className="stat-label">{label}</span>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* ──── Features ──────────────────────────────────────────── */}
      <section className="landing-section" aria-labelledby="features-heading">
        <div className="container">
          <span className="section-eyebrow">What you get</span>
          <h2 id="features-heading" className="section-heading">Everything a voter needs</h2>
          <p className="section-sub">
            VoteWise combines real-time ECI data with conversational AI
            to demystify India's election process.
          </p>
          <div className="features-grid">
            {FEATURES.map(f => (
              <article key={f.title} className="feature-card">
                <div className="feature-icon" aria-hidden="true">{f.icon}</div>
                <h3 className="feature-title">{f.title}</h3>
                <p className="feature-desc">{f.desc}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ──── Phases ────────────────────────────────────────────── */}
      <section className="landing-section" aria-labelledby="phases-heading">
        <div className="container">
          <span className="section-eyebrow">Election structure</span>
          <h2 id="phases-heading" className="section-heading">The 7 phases of an Indian election</h2>
          <p className="section-sub">
            From announcement to results — explore any phase in the dashboard for a full AI-powered breakdown.
          </p>
          <div className="phases-strip">
            {PHASES.map((p, i) => (
              <div key={p.num} className={`phase-tile ${i === 2 ? 'active-tile' : ''}`}>
                <p className="phase-tile-num">{p.num}</p>
                <p className="phase-tile-name">{p.name}</p>
              </div>
            ))}
          </div>
          <div className="phases-cta">
            <button
              id="explore-timeline-btn"
              className="btn btn-outline"
              onClick={() => navigate('/onboarding')}
            >
              Explore your state's timeline →
            </button>
          </div>
        </div>
      </section>

      {/* ──── Bottom CTA ────────────────────────────────────────── */}
      <section className="landing-section bottom-cta" aria-labelledby="cta-heading">
        <div className="container">
          <h2 id="cta-heading" className="bottom-cta-title">Ready to vote smarter?</h2>
          <p className="bottom-cta-sub">Takes 30 seconds to set up. No sign-in required.</p>
          <button
            id="final-cta-btn"
            className="btn btn-primary btn-hero-primary"
            onClick={() => navigate('/onboarding')}
          >
            Start now — it's free
          </button>
        </div>
      </section>

      {/* ──── Footer ────────────────────────────────────────────── */}
      <footer className="landing-footer">
        <div className="container">
          Built for Hack2Skill PromptWars × Google ·{' '}
          Verify critical dates at{' '}
          <a href="https://eci.gov.in" target="_blank" rel="noopener noreferrer">eci.gov.in</a>
        </div>
      </footer>

    </main>
  );
}
